baseURL         = "https://ichbinfrog.github.io/"
languageCode    = "en-us"
title           = "ichbinfrog"
theme           = "hello-friend-ng"
enableEmoji     = true
publishDir      = "./public"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  
  paginate = 10
  # Subtitle for home
  homeSubtitle = "Site Reliability Engineer @ Pricehubble"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Metadata mostly used in document's head
  description = "project page"
  keywords = "project, page"
  images = [""]
  customCSS = ["/css/post.css"]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ichbinfrog"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ichbinfrog/"

  [taxonomies]
    tag      = "tags"
    category = "categories"
    series   = "series"
    
[languages]
  [languages.en]
    title = "Hoang Quoc Trung"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ichbinfrog"
      logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "projects"
    name = "0_projects"
    url = "/projects"

  [[menu.main]]
    identifer  = "university"
    name       = "2_uni_works"
    url        = "/university"

  [[menu.main]]
    identifier = "internships"
    name       = "1_internships"
    url        = "/internships"
